use sakila;
show tables;

-- 1.List all actors from the actor table, showing their first and last names.
select first_name, last_name
from actor;

-- 2.List all films released in 2006 from the film table. Show only the film title and release year.
SELECT title, release_year
FROM film
WHERE release_year = 2006;

-- 3.Display the first 10 customers from the customer table, showing their customer ID, first name, last name, and email.
select first_name, last_name, email
from customer
limit 10;

-- 4.Show all cities located in the country “India” from the city and country tables.
select c.country, ct.city 
from country as c
inner join city as ct 
on c.country_id = ct.country_id
where c.country = "India";

-- 5.Retrieve the names of all stores and their managers.
select sf.first_name, sf.last_name
from store as st
inner join staff as sf
on st.store_id = sf.store_id;

-- 6. List all films along with their categories using a join between film, film_category, and category.
select f.title, c.name
from film as f
inner join film_category as fc
on f.film_id = fc.film_id
inner join category as c
on fc.category_id = c.category_id;

-- 7 Find the total number of rentals per customer using rental and customer tables.

Display the top 5 customers who spent the most money (use payment table).

Show all films that have “Comedy” as their category.

Retrieve the list of actors who appeared in the film “ACADEMY DINOSAUR”.

🚀 Advanced Level
Find the average rental duration per film category.

List all customers who have never rented a movie.

Display the top 3 cities with the highest number of rentals.

Find the most popular film (the one rented the most times).

Show the total revenue generated by each store.

