use sakila;
show tables;

-- 1.List all actors from the actor table, showing their first and last names.
select first_name, last_name
from actor;

-- 2.List all films released in 2006 from the film table. Show only the film title and release year.
SELECT title, release_year
FROM film
WHERE release_year = 2006;

-- 3.Display the first 10 customers from the customer table, showing their customer ID, first name, last name, and email.
select first_name, last_name, email
from customer
limit 10;

-- 4.Show all cities located in the country “India” from the city and country tables.
select c.country, ct.city 
from country as c
inner join city as ct 
on c.country_id = ct.country_id
where c.country = "India";

-- 5.Retrieve the names of all stores and their managers.
select sf.first_name, sf.last_name
from store as st
inner join staff as sf
on st.store_id = sf.store_id;

-- 6. List all films along with their categories using a join between film, film_category, and category.
select f.title, c.name
from film as f
inner join film_category as fc
on f.film_id = fc.film_id
inner join category as c
on fc.category_id = c.category_id;

-- 7 Find the total number of rentals per customer using rental and customer tables.
select concat(c.first_name, ' ', c.last_name) as Full_Name, count(r.rental_id) as Total_rental
from customer as c
join rental as r
on c.customer_id = r.customer_id
group by Full_Name;

-- 8 Display the top 5 customers who spent the most money (use payment table).
select concat(c.first_name, ' ', c.last_name) as Full_Name, sum(p.amount)
from customer as c
join payment as p
on c.customer_id = p.customer_id
group by Full_Name;

-- 9 Show all films that have “Comedy” as their category.
select f.title, c.name
from film as f
join film_category as fc
on f.film_id = fc.film_id
join category as c
on fc.category_id = c.category_id
where c.name = "comedy";

-- 10 Retrieve the list of actors who appeared in the film “ACADEMY DINOSAUR”
select a.first_name, a.last_name, f.title
from film as f
join film_actor as fa
on f.film_id = fa.film_id
join actor as a
on fa.actor_id = a.actor_id
where title = "ACADEMY DINOSAUR";


-- Advanced Level
-- 11 Find the average rental duration per film category.
select c.name, avg(rental_duration) as avg_rental_duration
from film as f
inner join film_category as fc
on f.film_id = fc.film_id
inner join category as c
on fc.category_id = c.category_id
group by c.name;

-- 12 List all customers who have never rented a movie.
select c.customer_id, concat(c.first_name, ' ', c.last_name) as fuul_name
from customer as c
left join rental as r
on c.customer_id = r.customer_id
where r.customer_id is Null;

-- 13. Display the top 3 cities with the highest number of rentals.
select city.city, count(r.customer_id) as Number_of_Rental
from rental as r
join customer as c
on r.customer_id = c.customer_id
join address as ad
on c.address_id = ad.address_id
join city 
on ad.city_id = city.city_id
group by city.city
order by Number_of_Rental desc
limit 3;

-- 14. Find the most popular film (the one rented the most times).
select f.title, count(r.rental_id) as Total_rented
from rental as r
join inventory as i
on r.inventory_id = i.inventory_id
join film as f
on i.film_id = f.film_id
group by f.title
order by Total_rented
limit 1;

-- 15. Show the total revenue generated by each store.
select * from payment;

select store.store_id, sum(amount) as Total_revenue
from payment as p
join staff
on p.staff_id = staff.staff_id
join store
on staff.store_id = store.store_id
group by store_id;


